# Generated by Django 2.2.9 on 2020-05-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='page',
            field=models.CharField(blank=True, max_length=255, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=455, verbose_name='Question'),
        ),
    ]
