# Generated by Django 2.2.10 on 2020-11-10 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20200522_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPageTypeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Page')),
                ('slug', models.SlugField(default='', editable=False, max_length=255, verbose_name='Slug')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page type',
                'verbose_name_plural': 'Page types',
            },
        ),
        migrations.RemoveField(
            model_name='questions',
            name='page',
        ),
        migrations.AlterField(
            model_name='questions',
            name='site',
            field=models.ManyToManyField(blank=True, to='main.WebsiteList', verbose_name='Websites'),
        ),
        migrations.AddField(
            model_name='questions',
            name='page',
            field=models.ManyToManyField(blank=True, to='main.QuestionPageTypeList', verbose_name='Pages'),
        ),
        migrations.CreateModel(
            name='QuestionsOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=255, verbose_name='Order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.QuestionPageTypeList', verbose_name='Page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.WebsiteList', verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Questions ordering',
                'verbose_name_plural': 'Questions ordering',
                'unique_together': {('page', 'site')},
            },
        ),
    ]
