# Generated by Django 2.2.10 on 2020-11-19 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201110_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='level',
            field=models.IntegerField(choices=[(1, 'Primary'), (2, 'Secondary')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='questionsordering',
            name='order',
            field=models.CharField(help_text='Comma-separated (e.g. 1,2,3,4,5)', max_length=255, verbose_name='Order'),
        ),
        migrations.CreateModel(
            name='SurveyOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(help_text='Comma-separated (e.g. 1,2,3,4,5)', max_length=255, verbose_name='Order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.QuestionPageTypeList', verbose_name='Page')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.WebsiteList', verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Survey ordering',
                'verbose_name_plural': 'Surveys ordering',
                'unique_together': {('page', 'site')},
            },
        ),
    ]
